// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAQ5sYTHh49rMpWFDQNzeD8_6I4W690chM',
    appId: '1:774428898846:web:0f3d5a195aff146a53a00f',
    messagingSenderId: '774428898846',
    projectId: 'shopapp-81795',
    authDomain: 'shopapp-81795.firebaseapp.com',
    storageBucket: 'shopapp-81795.appspot.com',
    measurementId: 'G-V4386YQRLQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCh7p3TYtW16IJJJdWSla7JvPkSc6VfiZM',
    appId: '1:774428898846:android:09b57308a882ee1453a00f',
    messagingSenderId: '774428898846',
    projectId: 'shopapp-81795',
    storageBucket: 'shopapp-81795.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB9uJlQykNMlzmr9wxBCqnYFtwhxYkNfNw',
    appId: '1:774428898846:ios:57f9135fb865f48f53a00f',
    messagingSenderId: '774428898846',
    projectId: 'shopapp-81795',
    storageBucket: 'shopapp-81795.appspot.com',
    iosBundleId: 'com.example.shopapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB9uJlQykNMlzmr9wxBCqnYFtwhxYkNfNw',
    appId: '1:774428898846:ios:57f9135fb865f48f53a00f',
    messagingSenderId: '774428898846',
    projectId: 'shopapp-81795',
    storageBucket: 'shopapp-81795.appspot.com',
    iosBundleId: 'com.example.shopapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAQ5sYTHh49rMpWFDQNzeD8_6I4W690chM',
    appId: '1:774428898846:web:57b8d3b61d4077af53a00f',
    messagingSenderId: '774428898846',
    projectId: 'shopapp-81795',
    authDomain: 'shopapp-81795.firebaseapp.com',
    storageBucket: 'shopapp-81795.appspot.com',
    measurementId: 'G-FNWVN54SRS',
  );
}
